#!/usr/bin/python3
# Generated by usbrply
# cmd: /usr/local/bin/usbrply --device-hi --vid 0x6130 --pid 0xfef0 --sleep --wrapper --comment --setup --halt -p data/sunday5.pcapng
import pygame

import binascii
import time
import usb1


def validate_read(expected, actual, msg):
    return
    if expected != actual:
        print('Failed %s' % msg)
        print('  Expected; %s' % binascii.hexlify(expected,))
        print('  Actual:   %s' % binascii.hexlify(actual,))
        #raise Exception('failed validate: %s' % msg)


def replay(dev):
    i = 0
    #def bulkRead(endpoint, length, timeout=None):
    #    return dev.bulkRead(endpoint, length, timeout=(1000 if timeout is None else timeout))

    #def bulkWrite(endpoint, data, timeout=None):
    #    dev.bulkWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))
    
    def controlRead(bRequestType, bRequest, wValue, wIndex, wLength, timeout=None):
        return
        return dev.controlRead(bRequestType, bRequest, wValue, wIndex, wLength,
                    timeout=(1000 if timeout is None else timeout))

    def controlWrite(bRequestType, bRequest, wValue, wIndex, data, timeout=None):
        
        print("--------------->0x%02x"%(bRequestType))
        if bRequestType in [0x21]:            
            dev.controlWrite(bRequestType, bRequest, wValue, wIndex, data, timeout=(1000 if timeout is None else timeout))
        else:
            print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")

    #def interruptRead(endpoint, size, timeout=None):
    #    return dev.interruptRead(endpoint, size, timeout=(1000 if timeout is None else timeout))

    #def interruptWrite(endpoint, data, timeout=None):
    #    dev.interruptWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))


    
    print("1")    
    # Generated from packet 842/843
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0C\x12\x00\x00\x67\xF5\x00\xE8\x80\x60\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.042)
    
    print("2")    
    # Generated from packet 844/845
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 844/845")
    time.sleep(0.003)
    
    print("3")    
    # Generated from packet 846/847
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\xAA\x20\x25\x11\x00\x00\x22\x67\xC8\x8E\x80\x60\x00\x58\x0C\x0D\xD3\x22\x21\x49\x24\x14\x85\xB6\x13\xBF\x70\x03\x0A\x80\x00\x00\x23\x02\x14\x36\x86\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 846/847")
    time.sleep(0.003)
    
    
    print("4")
    # Generated from packet 848/849
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 848/849")
    time.sleep(0.005)
    
    print("5")
    # Generated from packet 850/851
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0C\x12\x00\x01\x43\xE4\x00\xE8\x80\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.034)
    
    print("6")
    # Generated from packet 852/853
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 852/853")
    time.sleep(0.003)
    
    print("7")
    # Generated from packet 854/855
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\xAA\x20\x15\x11\x00\x01\x5B\x22\xF1\x8E\x80\x10\x00\x01\x03\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 854/855")
    time.sleep(0.014)
    
    print("8")
    # Generated from packet 856/857
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 856/857")
    time.sleep(0.013)
    
    print("9")
    # Generated from packet 858/859
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0C\x12\x00\x02\xA4\x16\x00\xE8\x80\x65\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.048)
    
    print("10")
    # Generated from packet 860/861
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 860/861")
    time.sleep(0.003)
    
    print("11")
    # Generated from packet 862/863
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\xAA\x20\x2E\x11\x00\x02\x28\x82\x9B\x8E\x80\x65\x00\x02\x00\x03\x02\x01\x03\x00\x01\x58\x0C\x0D\xD3\x22\x21\x49\x24\x14\x85\xB6\x13\xBF\x70\x03\x0A\x80\x00\x00\x23\x02\x14\x36\x86\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 862/863")
    time.sleep(0.090)
    
    print("12")
    # Generated from packet 864/865
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 864/865")
    time.sleep(0.010)
    
    
    print("13")
    # Generated from packet 866/867
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0C\x12\x00\x03\x66\x86\x00\xE8\x80\x63\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.041)
    
    print("14")
    # Generated from packet 868/869
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 868/869")
    time.sleep(0.077)
    
    
    print("15")
    # Generated from packet 870/871
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\xAA\x20\x1B\x11\x00\x03\xD9\x7C\x28\x8E\x80\x63\x00\x52\x4D\x4F\x57\x48\x59\x44\x31\x32\x35\x31\x53\x47\x41\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 870/871")
    time.sleep(0.912)
    
    print("16")
    # Generated from packet 872/873
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 872/873")
    time.sleep(0.003)
    
    print("17")
    # Generated from packet 874/875
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\x00", buff, "packet 874/875")
    time.sleep(0.108)
    
    print("18")
    # Generated from packet 876/877
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 876/877")
    time.sleep(0.058)
    
    print("19")
    # Generated from packet 878/879
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0C\x12\x00\x04\x20\x35\x00\xE3\x30\x92\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.109)
    
    print("20")
    # Generated from packet 880/881    
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 880/881")
    time.sleep(0.003)
    # Generated from packet 882/883
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\xAA\x20\x34\x13\x00\x04\xF6\x5B\xC0\x3E\x30\x92\x00\x01\x01\x00\x00\x00\x00\x00\x01\x00\x05\x00\x00\x00\x00\x9A\x99\x19\x3E\x01\x02\x01\x00\x00\x00\x14\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 882/883")    
    time.sleep(0.028)
    
    print("21")
    # Generated from packet 884/885
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 884/885")
    time.sleep(0.003)
    
    print("22")
    # Generated from packet 886/887
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\x00", buff, "packet 886/887")
    time.sleep(0.047)
    
    print("23")
    # Generated from packet 888/889
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 888/889")
    time.sleep(0.038)

    print("24")
    # Generated from packet 890/891
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0E\x12\x00\x05\xC5\x6E\x00\xE1\x13\xC2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.055)
    
    
    print("25")
    # Generated from packet 892/893
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 892/893")
    time.sleep(0.003)
    
    print("26")    
    # Generated from packet 894/895
    buff = controlRead(0xA1, 0x81, 0x0200, 0x0A00, 60)
    validate_read(b"\xAA\x00\x0E\x11\x00\x05\x55\xB4\x00\x1E\x13\xC2\x00\x01\x0C\x0D\xD3\x22\x21\x49\x24\x14\x85\xB6\x13\xBF\x70\x03\x0A\x80\x00\x00\x23\x02\x14\x36\x86\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 894/895")
    time.sleep(0.015)
    
    
    print("27")        
    # Generated from packet 896/897
    buff = controlRead(0xA1, 0x81, 0x0B00, 0x0100, 2)
    validate_read(b"\x00\x00", buff, "packet 896/897")
    time.sleep(0.003)

    print("28")        
    # Generated from packet 898/899
    buff = controlRead(0xA1, 0x81, 0x0B00, 0x0100, 2)
    validate_read(b"\x00\x00", buff, "packet 898/899")
    time.sleep(0.003)

    print("29")
    # Generated from packet 900/901
    buff = controlRead(0xA1, 0x85, 0x0300, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 900/901")
    time.sleep(0.003)
    
    
    print("30")
    # Generated from packet 902/903
    buff = controlRead(0xA1, 0x81, 0x0300, 0x0A00, 60)
    validate_read(b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 902/903")
    time.sleep(1.343)
    
    
    print("31")
    # Generated from packet 904/905
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 904/905")
    time.sleep(0.071)
    
    print("32")
    # Generated from packet 906/907
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0E\x10\x00\x06\xE4\xF3\x00\xE3\x30\x51\x00\x00\x00\x00\x20\x33\x54\xEA\xA9\x02\x00\x00\xFA\xA2\x39\x4E\x42\xDD\x01\x88\xA0\xC6\x2F\xEA\xA9\x02\x00\x00\x14\x35\xA9\x23\x00\x00\x00\x00\xE0\xC8\x2F\xEA\xA9\x02\x00\x00\xFC\xA2\x3F\x4E")
    time.sleep(0.117)

    print("33")
    # Generated from packet 908/909
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 908/909")
    time.sleep(0.049)
    
    
    print("34")
    # Generated from packet 910/911
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x07\x84\x2D\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xBB\x59\x1E\xBF\x84\x8E\x0A\x40\x00\x39\x00\x34\x00\x35\x00\x00\x00\x00\x00\xA9\x02\x00\x00\x0B\x1E\x43\x47\x00\x73\x03\x90\x90\xA6\x3C\xEA\xA9\x02\x00\x00\x19\x00\x00\x00")
    time.sleep(0.099)
    
    print("35")
    # Generated from packet 912/913
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 912/913")
    time.sleep(0.079)
    
    print("36")
    # Generated from packet 914/915
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x08\x96\xD5\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xBB\x59\x9E\xBF\xBB\x59\x1E\x40\x00\x70\x00\x67\x00\x00\x00\x00\x00\x65\x00\x74\x00\x00\x00\xB8\x1D\xFE\x44\x00\x42\x03\x97\xAA\x00\x19\x10\x00\x09\x34\x09\x00\xE3\x30\x23")
    time.sleep(0.506)
    
    
    print("37")
    # Generated from packet 916/917
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 916/917")
    time.sleep(0.040)
    # Generated from packet 918/919
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x09\x34\x09\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xBB\x59\x1E\xC0\x4F\x22\x83\x41\x00\x69\x00\x66\x00\x00\x00\xF0\xA6\x3C\xEA\xA9\x02\x00\x00\xBB\x1D\xF3\x44\x00\x43\x03\x80\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.107)
    
    print("38")
    # Generated from packet 920/921
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 920/921")
    time.sleep(0.018)
    
    print("39")
    # Generated from packet 922/923
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0A\x5A\x76\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x8F\x37\xF9\xC0\x96\xC5\xE7\x41\x00\x00\x00\x00\x00\x00\x00\x10\xAB\x3C\xEA\xA9\x02\x00\x00\x8C\x1E\xC2\x47\x00\x9E\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.114)
    
    print("40")
    # Generated from packet 924/925
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 924/925")
    time.sleep(0.102)
    
    
    print("41")
    # Generated from packet 926/927
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0B\x2A\x9F\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xE3\xC4\xDA\xC0\x67\xAF\xE9\x41\x00\x70\x00\x65\x00\x67\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\x45\x1F\x09\x46\x00\xB1\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.347)
    
    print("42")
    # Generated from packet 928/929
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 928/929")
    time.sleep(0.164)
    
    print("43")
    # Generated from packet 930/931
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0C\x60\x3D\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x23\xC5\xC5\xC0\x19\xDA\xEA\x41\x00\x00\x00\x00\x00\x00\x00\x10\xA5\x3C\xEA\xA9\x02\x00\x00\x7A\x1E\x3C\x47\x00\x58\x03\x90\xD0\x9F\x3C\xEA\xA9\x02\x00\x00\x19\x00\x00\x00")
    time.sleep(0.193)
    
    print("44")
    # Generated from packet 932/933
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 932/933")
    time.sleep(0.079)
    
    print("45")
    # Generated from packet 934/935
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0D\xE7\x28\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x89\xC8\xC7\xC0\xD4\xBE\xEA\x41\x50\x4E\x47\x0D\x0A\x1A\x0A\x00\xAC\x3C\xEA\xA9\x02\x00\x00\x5D\x1F\x11\x46\x00\xB9\x03\x80\x00\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00")
    time.sleep(0.221)
    
    print("46")
    # Generated from packet 936/937
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 936/937")
    time.sleep(0.076)
    
    print("47")
    # Generated from packet 938/939
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0E\x82\x44\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x23\xC5\xC5\xC0\x19\xDA\xEA\x41\x00\x75\x00\x72\x00\x00\x00\xC0\xA9\x3C\xEA\xA9\x02\x00\x00\x23\x1F\x6B\x46\x00\xBB\x03\x80\xC0\xAC\x3C\xEA\xA9\x02\x00\x00\x40\xAB\x3C\xEA")
    time.sleep(0.151)
    
    print("48")
    # Generated from packet 940/941
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 940/941")
    time.sleep(0.105)
    
    print("49")
    # Generated from packet 942/943
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0F\x53\x79\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x23\xC5\xC5\xC0\x19\xDA\xEA\x41\x00\x76\x00\x67\x00\x00\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\x9F\x1D\xD7\x44\x00\x4F\x03\x80\xB1\xA4\x3C\xEA\xA9\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.080)
    
    print("50")
    # Generated from packet 944/945
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 944/945")
    time.sleep(0.024)
    # Generated from packet 946/947
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x10\x2F\xF2\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x0E\xB7\xB2\xC0\xFA\xCD\xEB\x41\x00\x00\x00\x00\x00\x00\x00\x40\xB1\x3C\xEA\xA9\x02\x00\x00\x6D\x1F\x21\x46\x00\xA9\x03\x97\xAA\x00\x19\x10\x00\x13\x37\x68\x00\xE3\x30\x23")
    time.sleep(0.088)
    
    print("51")
    # Generated from packet 948/949
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 948/949")
    time.sleep(0.038)
    
    print("52")
    # Generated from packet 950/951
    # CLEAR_FEATURE (0x01): 0x200 (unknown)        
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x11\xFE\xCF\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x0E\xB7\xB2\xC0\xFA\xCD\xEB\x41\x55\xB9\x46\x99\xC4\x6E\x44\x72\x00\x61\x00\x00\x00\x00\x00\xB5\x12\xF9\x4B\x00\x41\x02\x88\x02\x00\x00\x00\x01\x00\x00\x00\x90\xC9\x57\xE5")
    time.sleep(0.044)
    
    print("53")
    # Generated from packet 952/953
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 952/953")
    time.sleep(0.010)
    
    print("54")
    # Generated from packet 954/955
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x12\xFC\xD7\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xFB\x41\xD7\xC1\xEE\x66\x19\x41\x00\x00\x00\x00\x00\x00\x00\x00\xB2\x3C\xEA\xA9\x02\x00\x00\x80\x1E\xF6\x47\x00\x9A\x03\x80\x61\xAF\x3C\xEA\xA9\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.047)
    
    
    print("55")
    # Generated from packet 956/957
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 956/957")
    time.sleep(0.136)
    
    print("56")
    # Generated from packet 958/959
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x13\x37\x68\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC6\xD5\xCF\xC1\x35\x6C\xF7\x40\x00\x75\x00\x72\x00\x00\x00\x10\xAB\x3C\xEA\xA9\x02\x00\x00\x70\x1F\x26\x46\x00\xAA\x03\x90\x20\xB1\x3C\xEA\xA9\x02\x00\x00\x01\x00\x00\x00")
    time.sleep(0.106)
    
    print("57")
    # Generated from packet 960/961
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 960/961")
    time.sleep(0.093)
    
    
    print("58")
    # Generated from packet 962/963
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x14\xE3\x5C\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC3\x76\xC3\xC1\x2A\xF0\xC5\x40\x00\x00\x00\x00\x00\xFF\xFF\xFF\xFF\xFF\x7F\x00\x00\x00\x00\x7D\x13\x31\x4A\x00\x59\x02\x90\x60\x6B\x4C\xE5\xA9\x02\x00\x00\x17\x73\xE2\xC4")
    time.sleep(0.126)
    
    print("59")
    # Generated from packet 964/965
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 964/965")
    time.sleep(0.039)
    
    print("60")
    # Generated from packet 966/967
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x15\x5D\xB4\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x0B\xBC\xEC\xC1\xB2\xD2\x9D\xC0\x00\x70\x00\x67\x00\x00\x00\xD0\xBD\x3C\xEA\xA9\x02\x00\x00\xC9\x1F\x8D\x46\x00\xDD\x03\x80\x00\x00\x00\x00\x08\x00\x00\x00\x09\x00\x00\x00")
    time.sleep(0.115)

    print("60")
    # Generated from packet 968/969
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 968/969")
    time.sleep(0.029)
    
    print("61")
    # Generated from packet 970/971
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x16\xDC\x2F\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x2D\x4F\xD2\xC1\xE8\xA8\x00\xC1\x10\x3A\xEA\xA9\x02\x00\x00\x00\x00\x7D\x00\x00\x00\x00\x00\xA3\x12\xEB\x4B\x00\x3B\x02\x97\xAA\x00\x19\x10\x00\x17\x0D\x12\x00\xE3\x30\x23")
    time.sleep(0.088)
    
    
    print("62")
    # Generated from packet 972/973
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 972/973")
    time.sleep(0.041)
    
    print("63")
    # Generated from packet 974/975
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x17\x0D\x12\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x2D\x4F\xD2\xC1\xE8\xA8\x00\xC1\x01\x3A\xEA\xA9\x02\x00\x00\x00\x00\x7D\x00\x00\x00\x00\x00\xA6\x12\xE8\x4B\x00\x3C\x02\x90\x80\x66\x30\xEA\xA9\x02\x00\x00\x98\xBA\xDC\xFE")
    time.sleep(0.150)
    
    
    print("64")
    # Generated from packet 976/977
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 976/977")
    time.sleep(0.067)
    
    
    print("65")
    # Generated from packet 978/979
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x18\xA0\xE0\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x5F\x5C\xCD\xC1\xE8\xA8\x00\xC1\x00\x00\x00\x00\x00\x00\x00\x10\xA8\x3C\xEA\xA9\x02\x00\x00\x7A\x1E\x3C\x47\x00\x58\x03\x80\x00\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00")
    time.sleep(0.112)
    
    print("66")
    # Generated from packet 980/981
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 980/981")
    time.sleep(0.030)
    
    print("67")
    # Generated from packet 982/983
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x19\x71\xDD\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x5F\x5C\xCD\xC1\xE8\xA8\x00\xC1\x6E\x67\x00\xFF\x7F\x00\x00\x90\xAC\x3C\xEA\xA9\x02\x00\x00\x8C\x1E\xC2\x47\x00\x9E\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.071)
    
    print("68")
    # Generated from packet 984/985
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 984/985")
    time.sleep(0.015)
    
    print("69")
    # Generated from packet 986/987
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1A\x9E\xB9\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x96\x27\xE1\xC1\x62\xBB\x59\xC0\x00\x00\x00\x00\x00\x00\x00\xD0\xB4\x3C\xEA\xA9\x02\x00\x00\x42\x1F\x34\x46\x00\xB0\x03\x97\xAA\x00\x19\x10\x00\x1D\x90\x7D\x00\xE3\x30\x23")
    time.sleep(0.085)
    
    print("70")
    # Generated from packet 988/989
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 988/989")
    time.sleep(0.011)
    
    print("71")
    # Generated from packet 990/991
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1B\x4F\x84\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x96\x27\xE1\xC1\x62\xBB\x59\xC0\x00\x00\x00\x00\x00\x00\x00\x70\xA5\x3C\xEA\xA9\x02\x00\x00\x4F\x1E\x07\x47\x00\x5F\x03\x80\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.078)
    
    print("72")
    # Generated from packet 992/993
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 992/993")
    time.sleep(0.035)
    
    print("73")
    # Generated from packet 994/995
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1C\x1B\x02\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x30\xAE\x5E\xC1\x84\x8E\x8A\xC1\x10\x3A\xEA\xA9\x02\x00\x00\x00\x00\x7D\x00\x00\x00\x00\x00\xA3\x12\xEB\x4B\x00\x3B\x02\x80\xAA\x00\x19\x10\x00\x17\x0D\x12\x00\xE3\x30\x23")
    time.sleep(0.089)
    
    print("74")
    # Generated from packet 996/997
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 996/997")
    time.sleep(0.077)
    
    print("75")
    # Generated from packet 998/999
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1D\x90\x7D\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xF3\x24\x32\xC0\xFB\x41\xD7\xC1\x00\x00\x00\x00\x00\x00\x00\xE0\xAD\x3C\xEA\xA9\x02\x00\x00\x45\x1F\x09\x46\x00\xB1\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.151)
    
    print("76")
    # Generated from packet 1000/1001
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1000/1001")
    time.sleep(0.028)
    
    print("77")
    # Generated from packet 1002/1003
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1E\x11\xC2\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xB2\xD2\x9D\x40\x0B\xBC\xEC\xC1\x00\x69\x00\x66\x00\x00\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\x8B\x1F\xC3\x46\x00\xF3\x03\x90\xD0\xBE\x3C\xEA\xA9\x02\x00\x00\x01\x00\x00\x00")
    time.sleep(0.055)
    
    print("78")
    # Generated from packet 1004/1005
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1004/1005")
    time.sleep(0.016)
    
    print("79")
    # Generated from packet 1006/1007
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1F\xBE\xBB\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x23\xC5\xC5\x40\x19\xDA\xEA\xC1\x00\x32\x00\x70\x00\x78\x00\x00\x00\x00\x00\x00\x00\x00\x00\xC2\x18\xB4\x41\x00\x30\x04\x80\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.115)
    
    
    print("80")
    # Generated from packet 1008/1009
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1008/1009")
    time.sleep(0.047)
    
    print("81")
    # Generated from packet 1010/1011
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x20\xB4\xAA\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x23\xC5\xC5\x40\x19\xDA\xEA\xC1\x00\x62\x00\x6D\x00\x70\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\x65\x1E\x29\x47\x00\x51\x03\x8C\x01\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x80")
    time.sleep(0.071)
    
    print("82")
    # Generated from packet 1012/1013
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1012/1013")
    time.sleep(0.010)
    
    print("83")
    # Generated from packet 1014/1015
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x21\x1B\x6B\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x85\x95\xD8\x40\xF5\xCF\xE9\xC1\x00\x00\x00\x00\x00\x00\x00\xC0\xAF\x3C\xEA\xA9\x02\x00\x00\x51\x1F\x05\x46\x00\xB5\x03\x80\x71\xAB\x3C\xEA\xA9\x02\x00\x00\x10\xB4\x3C\xEA")
    time.sleep(0.086)
    
    
    print("84")
    # Generated from packet 1016/1017
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1016/1017")
    time.sleep(0.049)
    
    
    print("85")
    # Generated from packet 1018/1019
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x22\xC0\x59\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xEE\x66\x19\x41\x94\xC8\x54\xC1\x00\x70\x00\x65\x00\x67\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\xF8\x1E\xBE\x47\x00\x82\x03\x80\x00\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00")
    time.sleep(0.144)
    
    print("86")
    # Generated from packet 1020/1021
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1020/1021")
    time.sleep(0.079)
    
    print("87")
    # Generated from packet 1022/1023
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x23\xA8\x23\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xCB\x93\x68\x41\xFD\xA0\xE3\xC0\x33\x78\x00\x78\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x59\x18\x1D\x41\x00\x0D\x04\x80\x00\x00\x00\x00\x08\x00\x00\x00\x09\x00\x00\x00")
    time.sleep(0.134)
    
    print("88")
    # Generated from packet 1024/1025
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1024/1025")
    time.sleep(0.070)
    
    print("89")
    # Generated from packet 1026/1027
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x24\x2A\xC8\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC5\x2B\xEF\x41\x84\x72\x1F\x40\x00\x00\x00\x00\x00\x00\x00\x60\xAF\x3C\xEA\xA9\x02\x00\x00\xD3\x1E\x9B\x47\x00\x8B\x03\x97\xAA\x00\x19\x10\x00\x28\x8F\xAD\x00\xE3\x30\x23")
    time.sleep(0.086)
    
    
    print("90")
    # Generated from packet 1028/1029
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1028/1029")
    time.sleep(0.007)
    
    print("91")
    # Generated from packet 1030/1031
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x25\xFB\xF5\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC5\x2B\xEF\x41\x84\x72\x1F\x40\xD1\x43\xE7\xA9\x02\x00\x00\x00\x00\x00\x00\x01\x02\x00\x00\x0E\x13\x40\x4A\x00\x74\x02\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.055)
    
    print("92")
    # Generated from packet 1032/1033
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1032/1033")
    time.sleep(0.004)
    
    print("93")
    # Generated from packet 1034/1035
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x26\xC8\xB1\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC5\x2B\xEF\x41\x84\x72\x1F\x40\x00\x00\x00\x00\x00\x00\x00\x40\x9F\x3C\xEA\xA9\x02\x00\x00\xE3\x1E\xAB\x47\x00\x7B\x03\x80\xA9\x9F\x3C\xEA\xA9\x02\x00\x00\xD0\x9F\x3C\xEA")
    time.sleep(0.033)
    
    print("94")
    # Generated from packet 1036/1037
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1036/1037")
    time.sleep(0.003)
    
    print("95")
    # Generated from packet 1038/1039
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x27\x19\x8C\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC5\x2B\xEF\x41\x84\x72\x1F\x40\x00\x00\x00\x00\x00\x00\x00\x80\xA4\x3C\xEA\xA9\x02\x00\x00\x58\x1E\x1E\x47\x00\x62\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.052)
    
    print("96")
    # Generated from packet 1040/1041
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1040/1041")
    time.sleep(0.004)
    
    print("97")
    # Generated from packet 1042/1043
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x28\x8F\xAD\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x32\x0D\xEB\x41\xBB\x59\x1E\x40\x6E\x67\x00\x66\x00\x00\x00\x90\xAC\x3C\xEA\xA9\x02\x00\x00\xD6\x1E\x98\x47\x00\x8C\x03\x80\x00\x00\x00\x00\x03\x00\x00\x00\x08\x00\x00\x00")
    time.sleep(0.038)
    
    print("98")
    # Generated from packet 1044/1045
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1044/1045")
    time.sleep(0.004)
    
    print("99")
    # Generated from packet 1046/1047
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x29\xC1\xC0\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC9\x34\xDC\x41\x84\x8E\x0A\x40\x00\x00\x00\x00\x00\x00\x00\x90\xA9\x3C\xEA\xA9\x02\x00\x00\x51\x1F\x05\x46\x00\xB5\x03\x80\x00\x00\x00\x00\x08\x00\x00\x00\x09\x00\x00\x00")
    time.sleep(0.166)
    
    print("100")
    # Generated from packet 1048/1049
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1048/1049")
    time.sleep(0.007)
    
    print("101")
    # Generated from packet 1050/1051
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2A\xF2\x84\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xC9\x34\xDC\x41\x84\x8E\x0A\x40\x6E\x67\x00\x00\x00\x00\x00\x74\x6F\x6E\x00\xA9\x02\x00\x00\xA0\x18\x96\x41\x00\x3A\x04\x80\x00\x00\x00\x00\x08\x00\x00\x00\x09\x00\x00\x00")
    time.sleep(0.114)
    
    
    print("102")
    # Generated from packet 1052/1053
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1052/1053")
    time.sleep(0.007)
    
    print("103")
    # Generated from packet 1054/1055
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2B\x20\x2B\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x5C\xFD\xC0\x41\x84\x8E\x0A\x40\x00\x70\x00\x65\x00\x67\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\x0B\x1E\x43\x47\x00\x73\x03\x80\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.041)
    
    print("104")
    # Generated from packet 1056/1057
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1056/1057")
    time.sleep(0.008)
    
    print("105")
    # Generated from packet 1058/1059
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2C\x97\x9E\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x5C\xFD\xC0\x41\x84\x8E\x0A\x40\x6E\x67\x00\x0D\x0A\x1A\x0A\x00\x3E\x49\xE5\xA9\x02\x00\x00\x78\x18\x3E\x41\x00\x02\x04\x80\x00\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00")
    time.sleep(0.038)
    
    print("106")
    # Generated from packet 1060/1061
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1060/1061")
    time.sleep(0.008)
    
    print("107")
    # Generated from packet 1062/1063
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2D\x46\xA3\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x5C\xFD\xC0\x41\x84\x8E\x0A\x40\x00\x75\x00\x72\x00\x00\x00\x73\x00\x65\x00\x64\x00\x00\x00\x34\x18\x7A\x41\x00\x16\x04\x80\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.041)
    
    print("108")
    # Generated from packet 1064/1065
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1064/1065")
    time.sleep(0.003)
    
    print("109")
    # Generated from packet 1066/1067
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2E\x43\x52\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xB9\xFA\x91\x41\x84\x8E\x0A\x40\x6E\x67\x00\x6E\x00\x73\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\xB8\x1D\xFE\x44\x00\x42\x03\x80\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.045)
    
    print("110")
    # Generated from packet 1068/1069
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1068/1069")
    time.sleep(0.005)
    
    print("111")
    # Generated from packet 1070/1071
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2F\xFA\xCC\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xF8\xE2\x4A\x41\x99\x86\x6D\x3F\x00\x00\x00\x00\x00\x00\x00\x00\xA3\x3C\xEA\xA9\x02\x00\x00\x58\x1E\x1E\x47\x00\x62\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.068)
    
    
    print("112")
    # Generated from packet 1072/1073
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1072/1073")
    time.sleep(0.005)
    
    print("113")
    # Generated from packet 1074/1075
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x30\xE3\xDF\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xEE\x66\x19\x41\x56\x36\x29\x26\x00\x00\x00\x00\x00\x00\x00\xD0\x9F\x3C\xEA\xA9\x02\x00\x00\x74\x1E\x3A\x47\x00\x56\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.045)
    
    
    print("114")
    # Generated from packet 1076/1077
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1076/1077")
    time.sleep(0.009)
    
    print("115")
    # Generated from packet 1078/1079
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x31\x3A\x3A\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x00\x00\x00\x00\x00\x00\x00\x00\x6E\x67\x00\x6E\x00\x73\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\xE3\x1E\xAB\x47\x00\x7B\x03\x80\xE8\xC6\x6A\x7E\xFF\x7F\x00\x00\xB0\x31\x37\xE7")
    time.sleep(0.047)
    
    print("116")
    # Generated from packet 1080/1081
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1080/1081")
    time.sleep(0.018)
    
    print("117")
    # Generated from packet 1082/1083
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0E\x10\x00\x32\xE5\x54\x00\xE3\x30\x51\x00\x01\x9B\x71\x4D\x00\x04\x00\x00\x00\x00\x00\x14\xA2\x67\x4E\x33\xCA\x01\x88\xA0\xDB\x2F\xEA\xA9\x02\x00\x00\x14\x35\xA9\x23\x00\x00\x00\x00\x20\xD1\x2F\xEA\xA9\x02\x00\x00\x16\xA2\x65\x4E")
    time.sleep(0.533)
    # Generated from packet 1084/1085
    buff = controlRead(0xA1, 0x85, 0x0600, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1084/1085")
    time.sleep(0.003)
    
    print("118")
    # Generated from packet 1086/1087
    buff = controlRead(0xA1, 0x81, 0x0600, 0x0A00, 60)
    validate_read(b"\x00\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 1086/1087")
    time.sleep(0.824)
    
    print("119")
    # Generated from packet 1088/1089
    buff = controlRead(0xA1, 0x85, 0x0600, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1088/1089")
    time.sleep(0.016)

    print("120")
    # Generated from packet 1090/1091
    # CLEAR_FEATURE (0x01): 0x600 (unknown)
    controlWrite(0x21, 0x01, 0x0600, 0x0A00, b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(2.538)
    
    
    print("121")
    # Generated from packet 1092/1093
    buff = controlRead(0xA1, 0x85, 0x0600, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1092/1093")
    time.sleep(0.003)

    print("122")
    # Generated from packet 1094/1095
    buff = controlRead(0xA1, 0x81, 0x0600, 0x0A00, 60)
    validate_read(b"\x00\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 1094/1095")
    time.sleep(0.583)
    


def open_dev(usbcontext=None):
    if usbcontext is None:
        usbcontext = usb1.USBContext()
    
    print('Scanning for devices...')
    for udev in usbcontext.getDeviceList(skip_on_error=True):
        vid = udev.getVendorID()
        pid = udev.getProductID()
        print("%04x:%04x"%(vid, pid))
        if (vid, pid) == (0x6e30, 0xfef0):
            print("")
            print("")
            print('Found device')
            print('Bus %03i Device %03i: ID %04x:%04x' % (
                udev.getBusNumber(),
                udev.getDeviceAddress(),
                vid,
                pid))
            print("aa")
            return udev.open()
    raise Exception("Failed to find a device")

if __name__ == "__main__":
    import argparse 
    
    parser = argparse.ArgumentParser(description='Replay captured USB packets')
    args = parser.parse_args()

    usbcontext = usb1.USBContext()
    usbdev = open_dev(usbcontext)
    for i in range(1):
        print(i)
        if usbdev.kernelDriverActive(i):
            print("detaching", i)
            usbdev.detachKernelDriver(i)
    
    usbdev.claimInterface(0)
    usbdev.resetDevice()
    


    background_colour = (255,255,255)
    (width, height) = (300, 200)
    screen = pygame.display.set_mode((width, height))
    pygame.display.set_caption('obsbot_tiny_reversing')
    screen.fill(background_colour)
    pygame.display.flip()
    running = True
    while running:
        
        pygame.mouse.set_pos = (400, 300)
        mouse_move = (0,0)
    
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_q or event.key == pygame.K_ESCAPE:
                    running = False

                if event.key == pygame.K_LEFT:
                    usbdev.controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x0E\x82\x44\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x23\xC5\xC5\xC0\x19\xDA\xEA\x41\x00\x75\x00\x72\x00\x00\x00\xC0\xA9\x3C\xEA\xA9\x02\x00\x00\x23\x1F\x6B\x46\x00\xBB\x03\x80\xC0\xAC\x3C\xEA\xA9\x02\x00\x00\x40\xAB\x3C\xEA", 1000)
                if event.key == pygame.K_RIGHT:
                    usbdev.controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1D\x90\x7D\x00\xE3\x30\x23\x03\x00\x00\x48\x43\xF3\x24\x32\xC0\xFB\x41\xD7\xC1\x00\x00\x00\x00\x00\x00\x00\xE0\xAD\x3C\xEA\xA9\x02\x00\x00\x45\x1F\x09\x46\x00\xB1\x03\x90\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00", 1000)
                if event.key == pygame.K_UP:
                    usbdev.controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x1B\x4F\x84\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x96\x27\xE1\xC1\x62\xBB\x59\xC0\x00\x00\x00\x00\x00\x00\x00\x70\xA5\x3C\xEA\xA9\x02\x00\x00\x4F\x1E\x07\x47\x00\x5F\x03\x80\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00", 1000)
                if event.key == pygame.K_DOWN:
                    usbdev.controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x2B\x20\x2B\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x5C\xFD\xC0\x41\x84\x8E\x0A\x40\x00\x70\x00\x65\x00\x67\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\x0B\x1E\x43\x47\x00\x73\x03\x80\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00", 1000)
                if event.key == pygame.K_r:
                    usbdev.controlWrite(0x21, 0x01, 0x0600, 0x0A00, b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 1000)
                    
            elif event.type == pygame.KEYUP:
                                                                  
                usbdev.controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\x31\x3A\x3A\x00\xE3\x30\x23\x03\x00\x00\x48\x43\x00\x00\x00\x00\x00\x00\x00\x00\x6E\x67\x00\x6E\x00\x73\x00\x00\x00\x3C\xEA\xA9\x02\x00\x00\xE3\x1E\xAB\x47\x00\x7B\x03\x80\xE8\xC6\x6A\x7E\xFF\x7F\x00\x00\xB0\x31\x37\xE7", 1000)
                print("up")
            
            if event.type == pygame.MOUSEMOTION:
                mouse_move = event.rel 
            if mouse_move != (0,0):
                print(mouse_move)