# Generated by usbrply
# cmd: /usr/local/bin/usbrply --device-hi --sleep --wrapper --comment --setup -p captures/up.pcapng

import binascii
import time
import usb1


def validate_read(expected, actual, msg):
    if expected != actual:
        print('Failed %s' % msg)
        print('  Expected; %s' % binascii.hexlify(expected,))
        print('  Actual:   %s' % binascii.hexlify(actual,))
        #raise Exception('failed validate: %s' % msg)


def replay(dev):
    def bulkRead(endpoint, length, timeout=None):
        return dev.bulkRead(endpoint, length, timeout=(1000 if timeout is None else timeout))

    def bulkWrite(endpoint, data, timeout=None):
        dev.bulkWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))
    
    def controlRead(bRequestType, bRequest, wValue, wIndex, wLength,
                    timeout=None):
        return dev.controlRead(bRequestType, bRequest, wValue, wIndex, wLength,
                    timeout=(1000 if timeout is None else timeout))

    def controlWrite(bRequestType, bRequest, wValue, wIndex, data,
                     timeout=None):
        dev.controlWrite(bRequestType, bRequest, wValue, wIndex, data,
                     timeout=(1000 if timeout is None else timeout))

    def interruptRead(endpoint, size, timeout=None):
        return dev.interruptRead(endpoint, size,
                    timeout=(1000 if timeout is None else timeout))

    def interruptWrite(endpoint, data, timeout=None):
        dev.interruptWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))

    # Generated by usbrply
    # Source: Linux pcap (usbmon)
    # cmd: /usr/local/bin/usbrply --device-hi --sleep --wrapper --comment --setup -p captures/up.pcapng
    # PCapGen device hi: selected device 5
    # Generated from packet 1/2
    buff = controlRead(0xA1, 0x85, 0x0600, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 1/2")
    time.sleep(0.003)
    # Generated from packet 3/4
    buff = controlRead(0xA1, 0x81, 0x0600, 0x0A00, 60)
    validate_read(b"\x00\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 3/4")
    time.sleep(1.296)
    # Generated from packet 5/6
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 5/6")
    time.sleep(0.025)
    # Generated from packet 7/8
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0E\x10\x00\xCE\x21\xC4\x00\xE3\x30\x51\x00\x00\x00\x00"
            b"\x80\x3B\xE3\x97\x6F\x02\x00\x00\x31\x6B\x92\x00\x44\x3A\x01\x90"
            b"\xF0\x40\x87\x97\x6F\x02\x00\x00\xD0\xA4\xBF\x94\x6F\x02\x00\x00"
            b"\x6F\x00\x6D\x00\x6D\x00\x65\x00\x33\x6B\x90\x00")
    time.sleep(0.035)
    # Generated from packet 9/10
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 9/10")
    time.sleep(0.010)
    # Generated from packet 11/12
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xCF\xB0\x2E\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xBB\x59\x1E\xBF\xBB\x59\x1E\xBF\x00\x62\x00\x6D\x00\x70\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x32\xFB\x6E\x09\x33\xD2\x03\x80"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x60\x49\x2F\x23")
    time.sleep(0.101)
    # Generated from packet 13/14
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 13/14")
    time.sleep(0.017)
    # Generated from packet 15/16
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD0\x78\xF3\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x62\xBB\xD9\xC0\xBB\x59\x1E\xC0\x48\x87\x97\x6F\x02\x00\x00"
            b"\xD0\x45\xCE\x97\x6F\x02\x00\x00\xE8\xFB\xB0\x09\x33\xC4\x03\x80"
            b"\x10\x4E\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.062)
    # Generated from packet 17/18
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 17/18")
    time.sleep(0.010)
    # Generated from packet 19/20
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD1\xAC\x05\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xC1\x17\x37\xC1\x2A\xF0\x45\xC0\x00\x75\x00\x72\x00\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x43\xFB\x19\x09\x33\xF7\x03\x80"
            b"\x70\x45\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.060)
    # Generated from packet 21/22
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 21/22")
    time.sleep(0.018)
    # Generated from packet 23/24
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD2\x36\xC9\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\x6D\xC1\x2A\xF0\x45\xC0\x00\x70\x00\x65\x00\x67\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x3E\xFB\x7A\x09\x33\xD6\x03\x8C"
            b"\x01\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x80")
    time.sleep(0.133)
    # Generated from packet 25/26
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 25/26")
    time.sleep(0.012)
    # Generated from packet 27/28
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD3\x9F\x8C\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x20\x74\x94\xC1\x84\x8E\x0A\xC0\x00\x00\x00\x00\x00\x00\x00"
            b"\x90\x46\xCE\x97\x6F\x02\x00\x00\x58\xFB\x00\x09\x33\xF4\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.125)
    # Generated from packet 29/30
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 29/30")
    time.sleep(0.015)
    # Generated from packet 31/32
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD4\xDE\x12\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x57\x3F\xA8\xC1\xBB\x59\x9E\xBF\x00\x00\x00\x00\x00\x00\x00"
            b"\x70\x45\xCE\x97\x6F\x02\x00\x00\x3E\xFB\x7A\x09\x33\xD6\x03\x8C"
            b"\x01\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x80")
    time.sleep(0.070)
    # Generated from packet 33/34
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 33/34")
    time.sleep(0.003)
    # Generated from packet 35/36
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD5\x7B\x0A\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x8F\x0A\xBC\xC1\xE6\x6B\xCF\x26\x33\x78\x00\x78\x00\x00\x00"
            b"\x10\x48\xCE\x97\x6F\x02\x00\x00\xC6\xFB\x92\x09\x33\xCE\x03\x80"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x60\x49\x2F\x23")
    time.sleep(0.075)
    # Generated from packet 37/38
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 37/38")
    time.sleep(0.011)
    # Generated from packet 39/40
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD6\x31\xA6\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x91\x69\xC8\xC1\x99\x86\x6D\x3F\x00\x63\x00\x6E\x00\x73\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x0D\xFB\x57\x09\x33\xE5\x03\x80"
            b"\xB0\x4D\xCE\x97\x6F\x02\x00\x00\xC0\x4C\xCE\x97")
    time.sleep(0.111)
    # Generated from packet 41/42
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 41/42")
    time.sleep(0.108)
    # Generated from packet 43/44
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD7\x3B\x96\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x94\xC8\xD4\xC1\xBB\x59\x9E\x3F\x00\x76\x00\x67\x00\x00\x00"
            b"\xB0\x4D\xCE\x97\x6F\x02\x00\x00\xB0\xFA\xE8\x0E\x33\xFC\x03\x80"
            b"\xA0\x4E\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.139)
    # Generated from packet 45/46
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 45/46")
    time.sleep(0.014)
    # Generated from packet 47/48
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD8\x27\x3B\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xC9\x34\xDC\xC1\xBB\x59\x9E\x3F\x00\x70\x00\x65\x00\x67\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\xB5\xFA\xEF\x0E\x33\xFD\x03\x80"
            b"\x40\x45\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.071)
    # Generated from packet 49/50
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 49/50")
    time.sleep(0.018)
    # Generated from packet 51/52
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xD9\x91\x55\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\xFF\xFF\xFF\xFF\xFF\x00"
            b"\x00\xFF\xFF\xFF\x00\x02\x00\x00\xE8\xFB\xB0\x09\x33\xC4\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.087)
    # Generated from packet 53/54
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 53/54")
    time.sleep(0.005)
    # Generated from packet 55/56
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xDA\xA2\x11\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\x70\x00\x65\x00\x67\x00"
            b"\x00\x00\x00\x00\x01\x02\x00\x00\x58\xFB\x00\x09\x33\xF4\x03\x80"
            b"\x00\x00\x00\x00\x08\x00\x00\x00\x09\x00\x00\x00")
    time.sleep(0.051)
    # Generated from packet 57/58
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 57/58")
    time.sleep(0.004)
    # Generated from packet 59/60
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xDB\x73\x2C\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\x10\x45\xCE\x97\x6F\x02\x00\x00\xE7\xFB\xBD\x09\xFF\xC3\x03\x80"
            b"\xAA\x00\x19\x10\x00\xD9\x91\x55\x00\xE3\x30\x23")
    time.sleep(0.063)
    # Generated from packet 61/62
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 61/62")
    time.sleep(0.003)
    # Generated from packet 63/64
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xDC\xC4\x99\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\x60\x4F\xCE\x97\x6F\x02\x00\x00\x52\xFB\x0E\x09\x33\xF2\x03\x80"
            b"\x30\x4F\xCE\x97\x6F\x02\x00\x00\xE0\x4D\xCE\x97")
    time.sleep(0.175)
    # Generated from packet 65/66
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 65/66")
    time.sleep(0.003)
    # Generated from packet 67/68
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xDD\x15\xA4\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\x76\x00\x67\x00\x7A\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x38\xFB\x60\x09\xFF\xD4\x03\x90"
            b"\x60\xFF\xAE\x92\x6F\x02\x00\x00\xB3\x90\x35\xF3")
    time.sleep(0.038)
    # Generated from packet 69/70
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 69/70")
    time.sleep(0.003)
    # Generated from packet 71/72
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xDE\x26\xE0\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x6E\x67\x00\x00\x00\x00\x00"
            b"\xF0\x4C\xCE\x97\x6F\x02\x00\x00\x29\xFB\x73\x09\xFF\xD9\x03\x90"
            b"\x70\x51\xB3\x92\x6F\x02\x00\x00\xB3\x90\x35\xF3")
    time.sleep(0.296)
    # Generated from packet 73/74
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 73/74")
    time.sleep(0.003)
    # Generated from packet 75/76
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xDF\xF7\xDD\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\x63\x00\x6E\x00\x73\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\xC6\xFB\x92\x09\x33\xCE\x03\x80"
            b"\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00")
    time.sleep(0.037)
    # Generated from packet 77/78
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 77/78")
    time.sleep(0.003)
    # Generated from packet 79/80
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE0\xFD\xCC\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCB\x93\xE8\xC1\xBB\x59\x9E\x3F\x00\x00\x00\xD6\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\xCB\xFB\x91\x09\x33\xCF\x03\x90"
            b"\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.051)
    # Generated from packet 81/82
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 81/82")
    time.sleep(0.015)
    # Generated from packet 83/84
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE1\x8E\x56\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x30\xAE\xDE\xC1\xBB\x59\x9E\x3F\x6E\x67\x00\x00\x00\x00\x00"
            b"\x40\x4E\xCE\x97\x6F\x02\x00\x00\x79\xFB\x23\x09\x33\xE9\x03\x80"
            b"\xE1\x44\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.041)
    # Generated from packet 85/86
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 85/86")
    time.sleep(0.003)
    # Generated from packet 87/88
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE2\x7D\x46\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x8C\xAB\xAF\xC1\xBB\x59\x9E\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\xA0\x45\xCE\x97\x6F\x02\x00\x00\x37\xFB\x6D\x09\x33\xD3\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.093)
    # Generated from packet 89/90
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 89/90")
    time.sleep(0.003)
    # Generated from packet 91/92
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE3\x8D\x28\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x4F\x22\x83\xC1\xBB\x59\x9E\x3F\x00\x65\x00\x62\x00\x70\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x7F\xFB\x25\x09\xFF\xEB\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.133)
    # Generated from packet 93/94
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 93/94")
    time.sleep(0.037)
    # Generated from packet 95/96
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE4\x46\xB8\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x2A\xF0\x45\xC1\xBB\x59\x9E\x3F\x00\x63\x00\x6F\x00\x00\x00"
            b"\x80\x50\xCE\x97\x6F\x02\x00\x00\x15\xFB\x4F\x09\x33\xDD\x03\x88"
            b"\x02\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x80")
    time.sleep(0.077)
    # Generated from packet 97/98
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 97/98")
    time.sleep(0.003)
    # Generated from packet 99/100
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE5\x29\xE1\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x84\x8E\x0A\xC1\x99\x86\x6D\x3F\x00\x69\x00\x66\x00\x66\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x0E\xFB\x2A\x09\x33\xE6\x03\x88"
            b"\x02\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x80")
    time.sleep(0.092)
    # Generated from packet 101/102
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 101/102")
    time.sleep(0.003)
    # Generated from packet 103/104
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE6\x58\xC6\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\xED\xC0\x99\x86\x6D\x3F\x6E\x67\x00\x00\x00\x00\x00"
            b"\x00\x46\xCE\x97\x6F\x02\x00\x00\xDF\xFB\x85\x09\xFF\xCB\x03\x80"
            b"\xF0\x4C\xCE\x97\x6F\x02\x00\x00\x20\x4A\xCE\x97")
    time.sleep(0.087)
    # Generated from packet 105/106
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 105/106")
    time.sleep(0.003)
    # Generated from packet 107/108
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE7\x8F\xC2\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x20\x74\x94\xC0\xF9\xC0\xA3\x25\x00\x70\x00\x65\x00\x67\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x79\xFB\x23\x09\x33\xE9\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.144)
    # Generated from packet 109/110
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 109/110")
    time.sleep(0.010)
    # Generated from packet 111/112
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE8\x2B\xF5\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x2A\xF0\x45\xC0\xBB\x59\x1E\xBF\x00\x70\x00\x67\x00\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x79\xFB\x23\x09\x33\xE9\x03\x80"
            b"\x69\x4F\xCE\x97\x6F\x02\x00\x00\x40\x48\xCE\x97")
    time.sleep(0.091)
    # Generated from packet 113/114
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 113/114")
    time.sleep(0.038)
    # Generated from packet 115/116
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xE9\x7B\x34\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xBB\x59\x1E\xC0\xBB\x59\x1E\xBF\x6E\x67\x00\x00\x00\x00\x00"
            b"\x60\x49\xCE\x97\x6F\x02\x00\x00\x15\xFB\x4F\x09\x33\xDD\x03\x88"
            b"\x02\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x80")
    time.sleep(0.135)
    # Generated from packet 117/118
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 117/118")
    time.sleep(0.005)
    # Generated from packet 119/120
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xEA\x48\x70\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xBB\x59\x1E\xC0\xBB\x59\x1E\xBF\x00\x00\x00\x00\x00\x00\x00"
            b"\xA0\x4B\xCE\x97\x6F\x02\x00\x00\x5D\xFB\x07\x09\xFF\xF5\x03\x90"
            b"\x60\xFF\xAE\x92\x6F\x02\x00\x00\xB3\x91\x35\xF3")
    time.sleep(0.063)
    # Generated from packet 121/122
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 121/122")
    time.sleep(0.022)
    # Generated from packet 123/124
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xEB\x99\x4D\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xBB\x59\x1E\xC0\xBB\x59\x1E\xBF\x00\x00\x00\x00\x00\x00\x00"
            b"\x70\x4E\xCE\x97\x6F\x02\x00\x00\x6C\xFB\x34\x09\x33\xF0\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.062)
    # Generated from packet 125/126
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 125/126")
    time.sleep(0.028)
    # Generated from packet 127/128
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xEC\x2E\xF8\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xBB\x59\x1E\xC0\xBB\x59\x1E\xBF\x4D\xCE\x97\x6F\x02\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x1B\xFB\x41\x09\xFF\xDF\x03\x8C"
            b"\x01\x00\x00\x00\x04\x00\x00\x00\x06\x00\x00\x80")
    time.sleep(0.071)
    # Generated from packet 129/130
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 129/130")
    time.sleep(0.009)
    # Generated from packet 131/132
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xED\xFA\x69\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\xED\xBF\xBB\x59\x1E\xBF\x00\x00\x00\x00\x00\x00\x01"
            b"\x00\x00\x00\x00\x01\x00\x00\x00\xCB\xFB\x91\x09\x33\xCF\x03\x90"
            b"\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.136)
    # Generated from packet 133/134
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 133/134")
    time.sleep(0.087)
    # Generated from packet 135/136
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xEE\xC9\x2D\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\xED\xBF\xBB\x59\x1E\xBF\x52\x87\x97\x6F\x02\x00\x00"
            b"\xF0\x4F\xCE\x97\x6F\x02\x00\x00\xED\xFB\xB7\x09\x33\xC5\x03\x80"
            b"\x51\x50\xCE\x97\x6F\x02\x00\x00\xE0\x4D\xCE\x97")
    time.sleep(0.070)
    # Generated from packet 137/138
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 137/138")
    time.sleep(0.035)
    # Generated from packet 139/140
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xEF\x18\x10\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\xED\xBF\xBB\x59\x1E\xBF\x50\x4E\x47\x0D\x0A\x1A\x0A"
            b"\x00\x4E\xCE\x97\x6F\x02\x00\x00\xDA\xFB\x86\x09\xFF\xCA\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.045)
    # Generated from packet 141/142
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 141/142")
    time.sleep(0.006)
    # Generated from packet 143/144
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF0\x75\x26\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\xED\xBF\xBB\x59\x9E\xBE\x8B\x8C\x23\xFF\x7F\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x32\xFB\x6E\x09\x33\xD2\x03\x80"
            b"\x30\x46\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.063)
    # Generated from packet 145/146
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 145/146")
    time.sleep(0.003)
    # Generated from packet 147/148
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF1\x3B\x4A\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x35\x6C\xF7\xC0\x2A\xF0\xC5\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\x10\x45\xCE\x97\x6F\x02\x00\x00\xD4\xFB\x8C\x09\x33\xC8\x03\x80"
            b"\xB1\x4D\xCE\x97\x6F\x02\x00\x00\x00\x4F\xCE\x97")
    time.sleep(0.092)
    # Generated from packet 149/150
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 149/150")
    time.sleep(0.003)
    # Generated from packet 151/152
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF2\x24\x8B\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF8\xE2\x4A\xC1\x2A\xF0\xC5\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\x50\x47\xCE\x97\x6F\x02\x00\x00\x0D\xFB\x57\x09\x33\xE5\x03\x80"
            b"\x00\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00")
    time.sleep(0.003)
    # Generated from packet 153/154
    buff = controlRead(0xA1, 0x85, 0x0600, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 153/154")
    time.sleep(0.003)
    # Generated from packet 155/156
    buff = controlRead(0xA1, 0x81, 0x0600, 0x0A00, 60)
    validate_read(b"\x00\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 155/156")
    time.sleep(0.135)
    # Generated from packet 157/158
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 157/158")
    time.sleep(0.179)
    # Generated from packet 159/160
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF3\xAF\xEE\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x1D\x15\x88\xC1\x2A\xF0\xC5\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\x40\x45\xCE\x97\x6F\x02\x00\x00\x0D\xFB\x57\x09\x33\xE5\x03\x80"
            b"\x40\x48\xCE\x97\x6F\x02\x00\x00\xF0\x4C\xCE\x97")
    time.sleep(0.055)
    # Generated from packet 161/162
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 161/162")
    time.sleep(0.044)
    # Generated from packet 163/164
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF4\x45\xF1\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\xB2\xC1\x2A\xF0\xC5\x3F\x00\x65\x00\x62\x00\x70\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x29\xFB\x73\x09\xFF\xD9\x03\x90"
            b"\x70\x51\xB3\x92\x6F\x02\x00\x00\xB3\x90\x35\xF3")
    time.sleep(0.053)
    # Generated from packet 165/166
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 165/166")
    time.sleep(0.039)
    # Generated from packet 167/168
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF5\xED\x55\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCC\x8A\xEF\xC1\x9B\x12\xED\xBF\x00\x65\x00\x62\x00\x70\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x43\xFB\x19\x09\x33\xF7\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.089)
    # Generated from packet 169/170
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 169/170")
    time.sleep(0.023)
    # Generated from packet 171/172
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF6\xE4\x50\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xA4\x60\xEF\xC1\x83\x32\x0A\xC0\x8B\x8C\x23\xFF\x7F\x00\x00"
            b"\x00\x49\xCE\x97\x6F\x02\x00\x00\x79\xFB\x23\x09\x33\xE9\x03\x90"
            b"\x60\x4C\xCE\x97\x6F\x02\x00\x00\x19\x00\x00\x00")
    time.sleep(0.072)
    # Generated from packet 173/174
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 173/174")
    time.sleep(0.007)
    # Generated from packet 175/176
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF7\x35\x6D\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xA4\x60\xEF\xC1\x83\x32\x0A\xC0\x00\x63\x00\x6F\x00\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\xD4\xFB\x8C\x09\x33\xC8\x03\x80"
            b"\x00\x00\x00\x00\x0D\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.136)
    # Generated from packet 177/178
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 177/178")
    time.sleep(0.003)
    # Generated from packet 179/180
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF8\xCB\x39\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xA4\x60\xEF\xC1\x83\x32\x0A\xC0\x8B\x8C\x23\xFF\x7F\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\xE7\xFB\xBD\x09\xFF\xC3\x03\x80"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x60\x49\x2F\x23")
    time.sleep(0.045)
    # Generated from packet 181/182
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 181/182")
    time.sleep(0.045)
    # Generated from packet 183/184
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xF9\x20\x45\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xCC\x8A\xEF\xC1\x9B\x12\xED\xBF\x00\x00\x00\x00\x00\x00\x00"
            b"\xB0\x4D\xCE\x97\x6F\x02\x00\x00\xE1\xFB\xBB\x09\x33\xC1\x03\x80"
            b"\xE1\x4D\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.060)
    # Generated from packet 185/186
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 185/186")
    time.sleep(0.014)
    # Generated from packet 187/188
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xFA\x63\xA6\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x5F\x5C\xCD\xC1\xBB\x59\x9E\x3F\x00\x00\x00\x00\x00\x00\x00"
            b"\x40\x45\xCE\x97\x6F\x02\x00\x00\x43\xFB\x19\x09\x33\xF7\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x08\x00\x00\x00")
    time.sleep(0.128)
    # Generated from packet 189/190
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 189/190")
    time.sleep(0.016)
    # Generated from packet 191/192
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xFB\x20\x24\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xC1\x17\xB7\xC1\x2A\xF0\xC5\x3F\x00\x69\x00\x66\x00\x00\x00"
            b"\x20\x50\xCE\x97\x6F\x02\x00\x00\xD3\xFB\x89\x09\x33\xC7\x03\x80"
            b"\x00\x00\x00\x00\x0D\x00\x00\x00\x00\x00\x00\x00")
    time.sleep(0.127)
    # Generated from packet 193/194
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 193/194")
    time.sleep(0.033)
    # Generated from packet 195/196
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xFC\x0B\xC0\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x99\x86\x6D\xC1\xC7\x00\x83\x26\x50\x4E\x47\x0D\x0A\x1A\x0A"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\xE7\xFB\xBD\x09\xFF\xC3\x03\x80"
            b"\xD0\x45\xCE\x97\x6F\x02\x00\x00\x00\x00\x00\x00")
    time.sleep(0.050)
    # Generated from packet 197/198
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 197/198")
    time.sleep(0.014)
    # Generated from packet 199/200
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xFD\x3F\x87\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x89\x4C\x23\xC1\x99\x86\xED\xBF\x00\x00\x00\x00\x00\x00\x00"
            b"\x90\x46\xCE\x97\x6F\x02\x00\x00\xBB\xFA\xE1\x0E\xFF\xFF\x03\x80"
            b"\x09\x46\xCE\x97\x6F\x02\x00\x00\x40\x48\xCE\x97")
    time.sleep(0.120)
    # Generated from packet 201/202
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 201/202")
    time.sleep(0.031)
    # Generated from packet 203/204
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xFE\x68\xB8\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x57\x3F\xA8\xC0\x62\xBB\x59\xC0\x00\x75\x00\x72\x00\x00\x00"
            b"\x00\x45\xCE\x97\x6F\x02\x00\x00\xB0\xFA\xE8\x0E\x33\xFC\x03\x80"
            b"\x90\x46\xCE\x97\x6F\x02\x00\x00\xC0\x4C\xCE\x97")
    time.sleep(0.038)
    # Generated from packet 205/206
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 205/206")
    time.sleep(0.005)
    # Generated from packet 207/208
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x00\xFF\xBB\x97\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x62\xBB\x59\xC0\x62\xBB\x59\xC0\x6E\x67\x00\x67\x00\x00\x00"
            b"\x80\x47\xCE\x97\x6F\x02\x00\x00\x1B\xFB\x41\x09\xFF\xDF\x03\x8C"
            b"\x01\x00\x00\x00\x04\x00\x00\x00\x06\x00\x00\x80")
    time.sleep(0.107)
    # Generated from packet 209/210
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 209/210")
    time.sleep(0.009)
    # Generated from packet 211/212
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x00\x03\x28\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\x62\xBB\x59\xC0\x00\x69\x00\x66\x00\x00\x00"
            b"\xF0\x4F\xCE\x97\x6F\x02\x00\x00\xDF\xFB\x85\x09\xFF\xCB\x03\x90"
            b"\xC0\x46\xCE\x97\x6F\x02\x00\x00\x19\x00\x00\x00")
    time.sleep(0.162)
    # Generated from packet 213/214
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 213/214")
    time.sleep(0.020)
    # Generated from packet 215/216
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x01\xD2\x15\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\x62\xBB\x59\xC0\x00\x00\x00\x00\x00\x00\x00"
            b"\x20\x4A\xCE\x97\x6F\x02\x00\x00\xB0\xFA\xE8\x0E\x33\xFC\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.075)
    # Generated from packet 217/218
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 217/218")
    time.sleep(0.007)
    # Generated from packet 219/220
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x02\xE1\x51\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\x62\xBB\x59\xC0\x00\x69\x00\x66\x00\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x51\xFB\x0B\x09\x33\xF1\x03\x90"
            b"\xE0\x4D\xCE\x97\x6F\x02\x00\x00\x19\x00\x00\x00")
    time.sleep(0.157)
    # Generated from packet 221/222
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 221/222")
    time.sleep(0.004)
    # Generated from packet 223/224
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x03\xD2\x5F\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\xF3\x24\x32\xC0\x00\x00\x00\x00\x00\x00\x00"
            b"\xD0\x45\xCE\x97\x6F\x02\x00\x00\xB5\xFA\xEF\x0E\x33\xFD\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.060)
    # Generated from packet 225/226
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 225/226")
    time.sleep(0.007)
    # Generated from packet 227/228
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x04\x31\xC2\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\x84\x8E\x0A\xC0\x00\x63\x00\x6F\x00\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\x3E\xFB\x7A\x09\x33\xD6\x03\x8C"
            b"\x01\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x80")
    time.sleep(0.065)
    # Generated from packet 229/230
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 229/230")
    time.sleep(0.004)
    # Generated from packet 231/232
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x05\x00\xAB\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\x2A\xF0\xC5\xBF\x00\x00\x00\x00\x00\x00\x00"
            b"\x80\x47\xCE\x97\x6F\x02\x00\x00\x79\xFB\x23\x09\x33\xE9\x03\x80"
            b"\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00")
    time.sleep(0.175)
    # Generated from packet 233/234
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 233/234")
    time.sleep(0.017)
    # Generated from packet 235/236
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x06\x33\xEF\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\xF3\x24\x32\xC0\x2A\xF0\xC5\xBF\x00\x67\x00\x61\x00\x00\x00"
            b"\xC0\x46\xCE\x97\x6F\x02\x00\x00\x15\xFB\x4F\x09\x33\xDD\x03\x88"
            b"\x02\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x80")
    time.sleep(0.039)
    # Generated from packet 237/238
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 237/238")
    time.sleep(0.007)
    # Generated from packet 239/240
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x19\x10\x01\x07\x79\xE7\x00\xE3\x30\x23\x03\x00\x00\x48"
            b"\x43\x00\x00\x00\x00\x00\x00\x00\x00\x00\x75\x00\x72\x00\x00\x00"
            b"\x00\x00\xCE\x97\x6F\x02\x00\x00\xB5\xFA\xEF\x0E\x33\xFD\x03\x80"
            b"\x00\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00")
    time.sleep(0.079)
    # Generated from packet 241/242
    buff = controlRead(0xA1, 0x85, 0x0200, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 241/242")
    time.sleep(0.003)
    # Generated from packet 243/244
    # CLEAR_FEATURE (0x01): 0x200 (unknown)
    controlWrite(0x21, 0x01, 0x0200, 0x0A00, b"\xAA\x00\x0E\x10\x01\x08\x81\x2F\x00\xE3\x30\x51\x00\x01\x63\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\xA1\x47\xD4\x44\x61\x12\x19\x75"
            b"\x2D\x04\x04\xF8\x17\x9F\x96\xF6\xC7\xEB\x1F\x46\x82\x7E\x00\x10"
            b"\x40\x30\xB4\x92\x6F\x02\x00\x00\xE0\x33\xB4\x92")
    time.sleep(2.234)
    # Generated from packet 245/246
    buff = controlRead(0xA1, 0x85, 0x0600, 0x0A00, 2)
    validate_read(b"\x3C\x00", buff, "packet 245/246")
    time.sleep(0.003)
    # Generated from packet 247/248
    buff = controlRead(0xA1, 0x81, 0x0600, 0x0A00, 60)
    validate_read(b"\x00\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 247/248")
    # PcapGen: generated 249 packets
    # PcapGen device filter: dropped 0 / 249 packets

def open_dev(usbcontext=None):
    if usbcontext is None:
        usbcontext = usb1.USBContext()
    
    print('Scanning for devices...')
    for udev in usbcontext.getDeviceList(skip_on_error=True):
        vid = udev.getVendorID()
        pid = udev.getProductID()
        if (vid, pid) == (0x0000, 0x0000):
            print("")
            print("")
            print('Found device')
            print('Bus %03i Device %03i: ID %04x:%04x' % (
                udev.getBusNumber(),
                udev.getDeviceAddress(),
                vid,
                pid))
            return udev.open()
    raise Exception("Failed to find a device")

if __name__ == "__main__":
    import argparse 
    
    parser = argparse.ArgumentParser(description='Replay captured USB packets')
    args = parser.parse_args()

    usbcontext = usb1.USBContext()
    dev = open_dev(usbcontext)
    dev.claimInterface(0)
    dev.resetDevice()
    replay(dev)


